import { type SelectQueryBuilder, sql } from "kysely";
import { jsonArrayFrom } from "kysely/helpers/postgres";

import { type BuilderRequirements, compile, type QueryResult } from "../query";
import { getPostgreSQLBuilder } from "./builder";

const REGULAR_TABLE_KIND = "r";
const VIEW_TABLE_KIND = "v";
const TABLE_KINDS = [REGULAR_TABLE_KIND, VIEW_TABLE_KIND] as const;
type TableKind = (typeof TABLE_KINDS)[number];

interface Database {
  /** column defaults */
  "pg_catalog.pg_attrdef": {
    /** default expression as a node tree, use pg_get_expr(adbin, adrelid) */
    adbin: string;
    /** column number */
    adnum: number;
    /** table identifier */
    adrelid: number;
  };
  /** columns */
  "pg_catalog.pg_attribute": {
    /**
     * generation flag for computed columns:
     * '' (empty) for regular columns,
     * 's' for STORED generated columns (Postgres GENERATED ALWAYS AS).
     */
    attgenerated: "" | "s";
    /**
     * identity column flag:
     * '' (empty) for regular columns,
     * 'a' for ALWAYS (GENERATED ALWAYS AS IDENTITY),
     * 'd' for BY DEFAULT (GENERATED BY DEFAULT AS IDENTITY).
     */
    attidentity: "" | "a" | "d";
    /** was the column dropped. dropped columns might not be 100% removed immediately. */
    attisdropped: boolean;
    /** column name */
    attname: string;
    /** NOT NULL constraint: true if the column has a NOT NULL constraint */
    attnotnull: boolean;
    /** column order number in its table */
    attnum: number;
    /** table/view identifier */
    attrelid: string;
    /** column datatype identifier */
    atttypid: string;
  };
  /** resources, e.g. tables, sequences, etc. */
  "pg_catalog.pg_class": {
    /** resource id */
    oid: number;
    /** resource kind: regular table, view */
    relkind: TableKind;
    /** resource name */
    relname: string;
    /** schema id */
    relnamespace: number;
  };
  /** constraints */
  "pg_catalog.pg_constraint": {
    /** if a foreign key, the referenced columns */
    confkey: number[];
    /** if a foreign key, the referenced table */
    confrelid: number;
    /**
     * an ordered array of columns included in the constraint.
     *
     * the columns are represented by their ordinal number (`attnum`) in their relation (table).
     *
     * @example `'{1,3}'` - a constraint with 2 columns, the 1st & 3rd in their table.
     */
    conkey: number[];
    /** relation (table) id which this constraint was created for */
    conrelid: number;
    /**
     * constraint type.
     *
     * `'p'` - primary key constraint.
     * `'f'` - foreign key constraint.
     */
    contype: "p" | "f" | (string & {});
  };
  /** enum types' values */
  "pg_catalog.pg_enum": {
    /** enum value */
    enumlabel: string;
    /** enum's type id */
    enumtypid: number;
  };
  /** schemas */
  "pg_catalog.pg_namespace": {
    /** schema name */
    nspname: string;
    /** schema id */
    oid: number;
  };
  /** datatypes */
  "pg_catalog.pg_type": {
    /** type id */
    oid: number;
    /** type name */
    typname: string;
    /** type's schema (aka namespace) id */
    typnamespace: number;
  };
}

/**
 * Returns a query that returns metadata for all user-defined tables and views in the database.
 */
export function getTablesQuery(
  requirements?: Omit<BuilderRequirements, "Adapter" | "QueryCompiler">,
) {
  return compile(
    getPostgreSQLBuilder<Database>(requirements)
      .selectFrom("pg_catalog.pg_class as cls")
      .innerJoin("pg_catalog.pg_namespace as ns", "cls.relnamespace", "ns.oid")
      .$call(excludeSystemTables)
      // regular tables or views
      .where("cls.relkind", "in", TABLE_KINDS)
      .select((eb) => [
        "ns.nspname as schema",
        "cls.relname as name",
        jsonArrayFrom(
          eb
            .selectFrom("pg_catalog.pg_attribute as att")
            .innerJoin("pg_catalog.pg_type as typ", "typ.oid", "att.atttypid")
            .innerJoin(
              "pg_catalog.pg_namespace as tns",
              "tns.oid",
              "typ.typnamespace",
            )
            .leftJoin("pg_catalog.pg_constraint as pk_con", (jb) =>
              jb
                .on("pk_con.contype", "=", "p")
                .onRef("pk_con.conrelid", "=", "cls.oid")
                .on((eb) => eb("att.attnum", "=", eb.fn.any("pk_con.conkey"))),
            )
            .leftJoin("pg_catalog.pg_constraint as fk_con", (jb) =>
              jb
                .on("fk_con.contype", "=", "f")
                .onRef("fk_con.conrelid", "=", "cls.oid")
                .on((eb) => eb("att.attnum", "=", eb.fn.any("fk_con.conkey"))),
            )
            .leftJoin(
              "pg_catalog.pg_class as fk_cls",
              "fk_cls.oid",
              "fk_con.confrelid",
            )
            .leftJoin(
              "pg_catalog.pg_namespace as fk_ns",
              "fk_ns.oid",
              "fk_cls.relnamespace",
            )
            .leftJoin("pg_catalog.pg_attribute as fk_att", (jb) =>
              jb
                .onRef("fk_att.attrelid", "=", "fk_cls.oid")
                // Use a callback for the .on() condition to ensure correct context for types
                .on((on_eb) =>
                  on_eb("fk_att.attnum", "=", on_eb.fn.any("fk_con.confkey")),
                ),
            )
            .leftJoin("pg_catalog.pg_attrdef as def", (jb) =>
              jb
                .onRef("def.adrelid", "=", "att.attrelid")
                .onRef("def.adnum", "=", "att.attnum"),
            )
            .whereRef("att.attrelid", "=", "cls.oid")
            // exclude system columns
            .where("att.attnum", ">=", 0)
            .where("att.attisdropped", "!=", true)
            .select([
              "att.attname as name",
              "fk_att.attname as fk_column",
              "fk_cls.relname as fk_table",
              "fk_ns.nspname as fk_schema",
              "tns.nspname as datatype_schema",
              "typ.typname as datatype",
            ])
            .select((eb) => [
              eb("att.attidentity", "!=", "")
                .or(
                  eb("def.adbin", "is not", null).and(
                    eb.fn("pg_get_expr", ["def.adbin", "def.adrelid"]),
                    "like",
                    "nextval(%",
                  ),
                )
                .$castTo<boolean>()
                .as("autoinc"),
              eb("att.attgenerated", "!=", "")
                .$castTo<boolean>()
                .as("computed"),
              eb
                .fn<string | null>("pg_get_expr", ["def.adbin", "def.adrelid"])
                .as("default"),
              eb("att.attnotnull", "!=", true)
                .$castTo<boolean>()
                .as("nullable"),
              eb.fn
                .coalesce(
                  eb
                    .selectFrom("pg_catalog.pg_enum as enm")
                    .whereRef("enm.enumtypid", "=", "typ.oid")
                    .select((eb) =>
                      eb.fn.jsonAgg(eb.ref("enm.enumlabel")).as("o"),
                    ),
                  sql<string[]>`'[]'`,
                )
                .as("options"),
              eb
                .fn<
                  number | null
                >("array_position", ["pk_con.conkey", "att.attnum"])
                .as("pk"),
            ]),
        ).as("columns"),
      ]),
  );
}

/**
 * For testing purposes.
 */
export function mockTablesQuery() {
  return [
    {
      schema: "zoo",
      name: "animals",
      columns: [
        {
          autoinc: true,
          computed: false,
          datatype: "int4",
          datatype_schema: "pg_catalog",
          default: "nextval('zoo.animals_id_seq'::regclass)",
          fk_column: null,
          fk_schema: null,
          fk_table: null,
          name: "id",
          nullable: false,
          options: [],
          pk: 1,
        },
        {
          autoinc: false,
          computed: false,
          datatype: "text",
          datatype_schema: "pg_catalog",
          default: null,
          fk_column: null,
          fk_schema: null,
          fk_table: null,
          name: "name",
          nullable: true,
          options: [],
          pk: null,
        },
      ],
    },
    {
      schema: "public",
      name: "users",
      columns: [
        {
          autoinc: true,
          computed: false,
          datatype: "int4",
          datatype_schema: "pg_catalog",
          default: "nextval('users_id_seq'::regclass)",
          fk_column: null,
          fk_schema: null,
          fk_table: null,
          name: "id",
          nullable: false,
          options: [],
          pk: 1,
        },
        {
          autoinc: false,
          computed: false,
          datatype: "timestamp",
          datatype_schema: "pg_catalog",
          default: "CURRENT_TIMESTAMP",
          fk_column: null,
          fk_schema: null,
          fk_table: null,
          name: "created_at",
          nullable: true,
          options: [],
          pk: null,
        },
        {
          autoinc: false,
          computed: false,
          datatype: "timestamp",
          datatype_schema: "pg_catalog",
          default: null,
          fk_column: null,
          fk_schema: null,
          fk_table: null,
          name: "deleted_at",
          nullable: true,
          options: [],
          pk: null,
        },
        {
          autoinc: false,
          computed: false,
          datatype: "varchar",
          datatype_schema: "pg_catalog",
          default: null,
          fk_column: null,
          fk_schema: null,
          fk_table: null,
          name: "role",
          nullable: true,
          options: [],
          pk: null,
        },
        {
          autoinc: false,
          computed: false,
          datatype: "varchar",
          datatype_schema: "pg_catalog",
          default: null,
          fk_column: null,
          fk_schema: null,
          fk_table: null,
          name: "name",
          nullable: true,
          options: [],
          pk: null,
        },
        {
          autoinc: false,
          computed: true,
          datatype: "text",
          datatype_schema: "pg_catalog",
          default: null,
          fk_column: null,
          fk_schema: null,
          fk_table: null,
          name: "name_role",
          nullable: false,
          options: [],
          pk: null,
        },
      ],
    },
    {
      schema: "public",
      name: "composite_pk",
      columns: [
        {
          autoinc: false,
          computed: false,
          datatype: "uuid",
          datatype_schema: "pg_catalog",
          default: "gen_random_uuid()",
          fk_column: null,
          fk_schema: null,
          fk_table: null,
          name: "id",
          nullable: false,
          options: [],
          pk: 1,
        },
        {
          autoinc: false,
          computed: false,
          datatype: "text",
          datatype_schema: "pg_catalog",
          default: null,
          fk_column: null,
          fk_schema: null,
          fk_table: null,
          name: "name",
          nullable: true,
          options: [],
          pk: 2,
        },
        {
          autoinc: false,
          computed: false,
          datatype: "timestamp",
          datatype_schema: "pg_catalog",
          default: "now()",
          fk_column: null,
          fk_schema: null,
          fk_table: null,
          name: "created_at",
          nullable: true,
          options: [],
          pk: null,
        },
      ],
    },
  ] as const satisfies QueryResult<typeof getTablesQuery>;
}

/**
 * Returns a query that returns the current timezone setting of the PostgreSQL database.
 */
export function getTimezoneQuery() {
  const builder = getPostgreSQLBuilder();

  return compile(
    builder.selectNoFrom(
      builder
        .fn<string>("current_setting", [sql.lit("timezone")])
        .as("timezone"),
    ),
  );
}

/**
 * For testing purposes.
 */
export function mockTimezoneQuery() {
  return [{ timezone: "UTC" }] as const satisfies QueryResult<
    typeof getTimezoneQuery
  >;
}

/**
 * We don't want PostgreSQL internals in introspection results. To be used in `$call`.
 */
function excludeSystemTables<
  T extends SelectQueryBuilder<
    Database & {
      ns: Database["pg_catalog.pg_namespace"];
      cls: Database["pg_catalog.pg_class"];
    },
    "ns" | "cls",
    object
  >,
>(qb: T): T {
  return qb
    .where(`ns.nspname`, `!~`, `^pg_`)
    .where(`ns.nspname`, `!=`, `information_schema`) as never;
}
